### ISSUE TITLE
Calculator is no longer in focus after opening.

### ISSUE THREAD

**Issue by jonolumb** [elementary/calculator#201]
## What Happened
When I open Calculator, I have to click on the white pane to input numbers/sums.

## Expected Behavior
In the past, the input pane was automatically selected (in focus) immediately after opening the app. This meant you could open the app and start typing immediately.

## Platform Information
elementary OS 6 with latest updates

Thanks for looking into this.

**Comment by jeremypw** [comment]
I find the entry is focused whether I open Calculator as a flatpak or a native install.  In your case, what *is* focused (if anything) if not the entry?

Ah, I found that this has already been fixed since the last release by #197. So I will close this as the fix will be released in due course. Thanks for taking time to report anyway.

**Comment by jonolumb** [comment]
Ah, great stuff. Glad this has been fixed. Thanks for your support.
