### ISSUE TITLE
Doesn't read point

### ISSUE THREAD

**Issue by ItsPossibleAlready** [elementary/calculator#92]
When I write number with point, Calculator say that " '.' is unknown ". And I can only with ',' , but in screenshots i see number with point.

https://raw.githubusercontent.com/elementary/calculator/master/data/screenshot.png

**Comment by HerrAugust** [comment]
Yes, I have the same problem. According to the calculator
10 / 0,01 = 1000 (correct, notice , )
10 / 0.01 = 10

**Comment by ItsPossibleAlready** [comment]
I hope that developers will answer to this issue.

**Comment by raibtoffoletto** [comment]
This is related to Issue #88 and it is driving me crazy!! Some cultures use `.` others use `,` for the decimal point, Calculator is taking it from the language and regional settings, however, in my opinion, it should accept both inputs as decimal and the output should be in the regional formatting.

I'm Brazilian, Living in Belgium (so using Euro and Commas as decimals) and I've used all my life Us International keyboards. In the keypad there is a dot, I would want to use it to calculate stuff, since having to move my hand from the keypad to the main keyboard just to use the comma is a wast of time.

LibreOffice does that automatically in Calc I input `1024.68` and it shows me `1.024,68` as it should be.
If my settings were set for US format it would just give me `1,024.68`... independently how I've inputted the decimal.
